name: Continuous deployment

on: 
 push:
  branches:    
    - Development
    - main

jobs: 
  CD-server1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: feature
         
      - name: sanity check
        run: |
         whoami

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3      

      - name: Download artifact from GitHub releases
        run: gh release download "alpha" -p "alpha.zip" -D "."        
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Extract the artifact
        run: Expand-Archive -LiteralPath "alpha.zip" -DestinationPath ".\alpha" -Force

      - name: Deploy artifact to IIS path
        run: Copy-Item ".\alpha\Out\*"  -Destination "D:\IIS\web-app-test\" -Recurse -Force  


